exp_mode: 0
depth_mode: bin
author: xinyi
height: 1544
width: 2064
obj_height: 8
table_distance: 1195
calibmat_path: /home/hlab/bpbot/data/calibration/calibmat.txt
pick:
  height:
    max: 0.053012736791248294
    min: -0.04901074964897156
  area:
    left: 811
    top: 371
    right: 1647
    bottom: 1038
drop:
  height:
    max: 0.04533891982656879
    min: 0.010372077580194539
  area:
    left: 1440
    top: 314
    right: 1902
    bottom: 824
graspability:
  rotation_step: 45
  depth_step: 10
  hand_depth: 10
hand:
  left:
    type: schunk
  right:
    type: smc_ft
tangle:
  compressed_size: 250
  len_thld: 15
  dist_thld: 3
  sliding_size: 225
  sliding_stride: 10
