exp_mode: 0
depth_mode: bin
author: xinyi
height: 1544
width: 2064
obj_height: 8
table_distance: 1195
calibmat_path: /home/hlab/bpbot/data/calibration/calibmat.txt
pick:
  distance:
    max: 0
    min: -15
  margin:
    left: 848
    top: 416
    right: 1296
    bottom: 918
drop:
  distance:
    max: 1125
    min: 1075
  margin:
    left: 1393
    top: 416
    right: 1868
    bottom: 943
graspability:
  rotation_step: 45.0
  depth_step: 10
  hand_depth: 25
hand:
  left:
    type: schunk
  right:
    type: smc_ft
tangle:
  compressed_size: 250
  len_thld: 15
  dist_thld: 3
  sliding_size: 100
  sliding_stride: 20
