exp_mode: 0
height: 1544
width: 2064
obj_height: 5
author: xinyi
calibmat_path: /home/hlab/bpbot/data/calibration/calibmat.txt
pick:
  distance:
    max: 1120
    min: 1074
  margin:
    left: 652
    top: 358
    right: 1080
    bottom: 851
drop:
  distance:
    max: 1135
    min: 1074
  margin:
    left: 1183
    top: 366
    right: 1651
    bottom: 866
graspability:
  rotation_step: 22.5
  depth_step: 10
  hand_depth: 25
hand:
  schunk:
    template_size: 500
    finger_height: 12
    finger_width: 5
    open_width: 34
    tool_changer_height: 31
    flange_height: 6
    gripper_height: 48
    finger_length: 80
  smc:
    template_size: 500
    finger_height: 8
    finger_width: 4
    open_width: 46
    tool_changer_height: 31
    flange_height: 3
    gripper_height: 25
    finger_length: 80
  smc_length: 0.139
  schunk_length: 0.165
tangle:
  compressed_size: 250
  length_thre: 15
  distance_thre: 3
  sliding_size: 100
  sliding_stride: 20
