exp_mode: 0
depth_mode: table 
author: xinyi
height: 1544
width: 2064
obj_height: 8
table_distance: 1195  
calibmat_path: /home/hlab/bpbot/data/calibration/calibmat.txt
pick:
  distance:
    max: 1180
    min: 1090
  margin:
    left: 706
    top: 323
    right: 1801
    bottom: 1261
drop:
  distance:
    max: 1122
    min: 1073
  margin:
    left: 1171
    top: 382
    right: 1683
    bottom: 932
graspability:
  rotation_step: 45.0
  depth_step: 10
  hand_depth: 25
hand:
  left:
    type: smc_ft
  right:
    type: schunk
tangle:
  compressed_size: 250
  len_thld: 15
  dist_thld: 3
  sliding_size: 100
  sliding_stride: 20
