exp_mode: 0
depth_mode: bin
author: xinyi
height: 1544
width: 2064
obj_height: 8
table_distance: 1195
calibmat_path: /home/hlab/bpbot/data/calibration/calibmat.txt
pick:
  height:
    max: -0.04514108846934506
    min: -0.0496906510970363
  area:
    left: 1
    top: 2
    right: 3
    bottom: 4
drop:
  height:
    max: 10
    min: 0
  area:
    left: 5
    top: 6
    right: 7
    bottom: 8
graspability:
  rotation_step: 45.0
  depth_step: 10
  hand_depth: 25
hand:
  left:
    type: schunk
  right:
    type: smc_ft
tangle:
  compressed_size: 250
  len_thld: 15
  dist_thld: 3
  sliding_size: 100
  sliding_stride: 20
